### ISSUE TITLE
qq登录功能有bug

### ISSUE THREAD

**Issue by watashiymy** [itning/Student-Homework-Management-System#20]
通过qq登录的功能用不了，好像是**redirect_URI=http://shw.itning.top/qqLoginAfter**的问题

**Comment by itning** [comment]
在这里更改回调地址：[https://github.com/itning/Student-Homework-Management-System/blob/master/src/main/resources/qqconnectconfig.properties#L3](https://github.com/itning/Student-Homework-Management-System/blob/master/src/main/resources/qqconnectconfig.properties#L3)

**Comment by watashiymy** [comment]
> 在这里更改回调地址：https://github.com/itning/Student-Homework-Management-System/blob/master/src/main/resources/qqconnectconfig.properties#L3

回调地址要改成啥

**Comment by itning** [comment]
> > 在这里更改回调地址：https://github.com/itning/Student-Homework-Management-System/blob/master/src/main/resources/qqconnectconfig.properties#L3
> 
> 回调地址要改成啥

你需要申请QQ互联 然后 把这个地址改成你的回调地址
