### ISSUE TITLE
项目不错啊。

### ISSUE THREAD

**Issue by yelj** [itning/Student-Homework-Management-System#5]
但是功能逻辑有点不行啊。。

**Comment by itning** [comment]
这是很久之前一个项目啦,基本功能CRUD,上传下载,打压缩包下载,第三方登陆都有的
或许,你可以试试这个
<https://github.com/itning/shw_server>
<https://github.com/itning/shw_client>

**Comment by yelj** [comment]
> 这是很久之前一个项目啦,基本功能CRUD,上传下载,打压缩包下载,第三方登陆都有的
> 或许,你可以试试这个
> https://github.com/itning/shw_server
> https://github.com/itning/shw_client

好的，谢谢啊。。我来试试看。。

**Comment by yelj** [comment]
我看有个小程序挺好的，做了一个发布作业。。。。你可以和他的那个对接一下。
不过我觉得正常还需要一个学生在手机上 上传作业的 程序。。

**Comment by itning** [comment]
> 我看有个小程序挺好的，做了一个发布作业。。。。你可以和他的那个对接一下。
> 不过我觉得正常还需要一个学生在手机上 上传作业的 程序。。

手机上传作业么

**Comment by yelj** [comment]
> > 我看有个小程序挺好的，做了一个发布作业。。。。你可以和他的那个对接一下。
> > 不过我觉得正常还需要一个学生在手机上 上传作业的 程序。。
> 
> 手机上传作业么

他做的是 用手机发布作业。。没做 作业提交。。

**Comment by yelj** [comment]
https://github.com/LittleBitCode/homework 这个
