### ISSUE TITLE
可否提供详细部署步骤

### ISSUE THREAD

**Issue by tomriddle1234** [itning/Student-Homework-Management-System#6]
对不熟悉Java和tomcat的人来讲，怎么运行这个后台呢？
可否提供详细的部署步骤？

**Comment by itning** [comment]
在[README](https://github.com/itning/Student-Homework-Management-System/blob/master/README.md#部署)已经详细说明部署流程。

如果不熟悉Java建议先学习基础语法，然后学习J2EE相关知识。
